"""empty message

Revision ID: 597435b8bc41
Revises: 9e753a422f88
Create Date: 2021-12-10 14:49:57.137239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597435b8bc41'
down_revision = '9e753a422f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sjtu_carbon_emission____prj_main',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('prj_create_t', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('prj_creator', sa.String(length=255), nullable=True, comment='创建人'),
    sa.Column('last_refresh_t', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('prj_process_text', sa.String(length=255), nullable=True, comment='项目进度说明'),
    sa.Column('prj_process_int', sa.Integer(), nullable=True, comment='项目进度条'),
    sa.Column('prj_run_state_text', sa.String(length=255), nullable=True, comment='运行状态'),
    sa.Column('prj_run_error_text', sa.String(length=255), nullable=True, comment='报错信息'),
    sa.Column('prj_note', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prj_name')
    )
    op.create_table('sjtu_carbon_emission_input1_region_msw_generation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c1_sjtu_name', sa.String(length=50), nullable=True, comment='名称'),
    sa.Column('c2_sjtu_year', sa.String(length=50), nullable=True, comment='年份'),
    sa.Column('c3_sjtu_ssp', sa.String(length=50), nullable=True, comment='ssp类别'),
    sa.Column('c4_sjtu_msw', sa.Float(), nullable=True, comment='垃圾产量'),
    sa.Column('c5_sjtu_landfill', sa.Float(), nullable=True, comment='填埋处理'),
    sa.Column('c6_sjtu_incineration', sa.Float(), nullable=True, comment='焚烧处理'),
    sa.Column('c7_sjtu_compost', sa.Float(), nullable=True, comment='生物处理'),
    sa.Column('c8_3sjtu_recycling', sa.Float(), nullable=True, comment='回收处理'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_carbon_emission_input2_region_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c1_sjtu_region_name', sa.String(length=50), nullable=True, comment='地区'),
    sa.Column('c2_sjtu_region_en', sa.String(length=50), nullable=True, comment='对应'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_carbon_emission_input3_regionfactor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c1_sjtu_region_name', sa.String(length=50), nullable=True, comment='地区'),
    sa.Column('c2_sjtu_region_level', sa.String(length=50), nullable=True, comment='地区级别'),
    sa.Column('c3_sjtu_ssp', sa.String(length=50), nullable=True, comment='ssp类别'),
    sa.Column('c4_incineration_ch4', sa.Float(), nullable=True, comment='填埋CH4'),
    sa.Column('c5_incineration_co2', sa.Float(), nullable=True, comment='焚烧CO2'),
    sa.Column('c6_incineration_n2o', sa.Float(), nullable=True, comment='焚烧N2O'),
    sa.Column('c7_incineration_fuel_co2', sa.Float(), nullable=True, comment='焚烧燃料CO2'),
    sa.Column('c8_incineration_fuel_ch4', sa.Float(), nullable=True, comment='焚烧燃料CH4'),
    sa.Column('c9_incineration_fuel_n2o', sa.Float(), nullable=True, comment='焚烧燃料N2O'),
    sa.Column('c10_incineration_electricity_co2', sa.Float(), nullable=True, comment='焚烧发电CO2'),
    sa.Column('c11_bio_compost_ch4', sa.Float(), nullable=True, comment='堆肥CH4'),
    sa.Column('c12_bio_compost_n2o', sa.Float(), nullable=True, comment='堆肥N2O'),
    sa.Column('c13_bio_digest_ch4', sa.Float(), nullable=True, comment='厌氧消化CH4'),
    sa.Column('c14_electricity_c2o', sa.Float(), nullable=True, comment='发电CO2'),
    sa.Column('c15_ferterlizer_c2o', sa.Float(), nullable=True, comment='制肥CO2'),
    sa.Column('c16_recycle_c2o', sa.Float(), nullable=True, comment='回收CO2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_carbon_emission_input4_region_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c1_sjtu_district', sa.String(length=50), nullable=True, comment='地区'),
    sa.Column('c2_sjtu_en_name', sa.String(length=50), nullable=True, comment='英文'),
    sa.Column('c3_short_written', sa.String(length=50), nullable=True, comment='简写'),
    sa.Column('c4_belong_place', sa.String(length=50), nullable=True, comment='所属区域'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_carbon_emission_output1_carbon_emission_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('a1_sjtu_name', sa.String(length=50), nullable=True, comment='名称'),
    sa.Column('a2_sjtu_year', sa.String(length=50), nullable=True, comment='年份'),
    sa.Column('a3_sjtu_ssp', sa.String(length=50), nullable=True, comment='ssp类别'),
    sa.Column('a4_sjtu_msw', sa.Float(), nullable=True, comment='垃圾产量'),
    sa.Column('e0', sa.Float(), nullable=True, comment='填埋处理'),
    sa.Column('e1', sa.Float(), nullable=True, comment='焚烧处理'),
    sa.Column('e2', sa.Float(), nullable=True, comment='生物处理'),
    sa.Column('e3', sa.Float(), nullable=True, comment='回收处理'),
    sa.Column('e4', sa.Float(), nullable=True, comment='填埋排放'),
    sa.Column('e5', sa.Float(), nullable=True, comment='焚烧排放'),
    sa.Column('e6', sa.Float(), nullable=True, comment='焚烧净排'),
    sa.Column('e7', sa.Float(), nullable=True, comment='生物排放'),
    sa.Column('e8', sa.Float(), nullable=True, comment='生物净排'),
    sa.Column('e9', sa.Float(), nullable=True, comment='总排放'),
    sa.Column('e10', sa.Float(), nullable=True, comment='总净排放'),
    sa.Column('e11', sa.Float(), nullable=True, comment='填埋CH4'),
    sa.Column('e12', sa.Float(), nullable=True, comment='焚烧CO2'),
    sa.Column('e13', sa.Float(), nullable=True, comment='焚烧N2O'),
    sa.Column('e14', sa.Float(), nullable=True, comment='焚烧燃料CO2'),
    sa.Column('e15', sa.Float(), nullable=True, comment='焚烧发电CO2'),
    sa.Column('e16', sa.Float(), nullable=True, comment='堆肥CH4'),
    sa.Column('e17', sa.Float(), nullable=True, comment='堆肥N2O'),
    sa.Column('e18', sa.Float(), nullable=True, comment='厌氧消化CH4'),
    sa.Column('e19', sa.Float(), nullable=True, comment='发电CO2'),
    sa.Column('e20', sa.Float(), nullable=True, comment='制肥CO2'),
    sa.Column('e21', sa.Float(), nullable=True, comment='回收CO2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_pmedian____prj_main',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('prj_create_t', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('prj_creator', sa.String(length=255), nullable=True, comment='创建人'),
    sa.Column('last_refresh_t', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('prj_process_text', sa.String(length=255), nullable=True, comment='项目进度说明'),
    sa.Column('prj_process_int', sa.Integer(), nullable=True, comment='项目进度条'),
    sa.Column('prj_run_state_text', sa.String(length=255), nullable=True, comment='运行状态'),
    sa.Column('prj_run_error_text', sa.String(length=255), nullable=True, comment='报错信息'),
    sa.Column('prj_note', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prj_name')
    )
    op.create_table('sjtu_pmedian_input1_basic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='参数名称'),
    sa.Column('value', sa.Float(), nullable=True, comment='参数值'),
    sa.Column('unit', sa.String(length=255), nullable=True, comment='单位'),
    sa.Column('note', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_pmedian_input2_transferstation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('sub_names', sa.String(length=255), nullable=True, comment='名称'),
    sa.Column('weight_percentage', sa.Float(), nullable=True, comment='重量占比因子'),
    sa.Column('lng', sa.Float(), nullable=True, comment='经度'),
    sa.Column('lat', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('district', sa.String(length=255), nullable=True, comment='所属区'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_pmedian_input3_recyclingcenter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('district', sa.String(length=255), nullable=True, comment='区'),
    sa.Column('sub_district', sa.String(length=255), nullable=True, comment='街镇'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='位置'),
    sa.Column('lng', sa.Float(), nullable=True, comment='经度'),
    sa.Column('lat', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('max_load', sa.Integer(), nullable=True, comment='最大容量'),
    sa.Column('max_load_unit', sa.String(length=255), nullable=True, comment='最大容量单位'),
    sa.Column('has_selected', sa.Integer(), nullable=True, comment='是否选择'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_pmedian_input4_costmatrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('ts_name', sa.String(length=255), nullable=True, comment='中转站'),
    sa.Column('rrc_name', sa.String(length=255), nullable=True, comment='集散场'),
    sa.Column('cost', sa.String(length=255), nullable=True, comment='费用'),
    sa.Column('cost_unit', sa.String(length=255), nullable=True, comment='单位'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_pmedian_output_1_allocationmatrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('ts', sa.String(length=255), nullable=True, comment='中转站'),
    sa.Column('rrc', sa.String(length=255), nullable=True, comment='集散场'),
    sa.Column('p_value', sa.Integer(), nullable=True, comment='p值'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_pmedian_output_2_buildscale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('p_value', sa.Integer(), nullable=True, comment='p值'),
    sa.Column('rrc', sa.String(length=255), nullable=True, comment='集散场'),
    sa.Column('rrc_scale', sa.Integer(), nullable=True, comment='规模'),
    sa.Column('scale_unit', sa.String(length=255), nullable=True, comment='规模单位'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjtu_pmedian_output_3_costmatrix',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('p', sa.Integer(), nullable=True, comment='p值'),
    sa.Column('transport_cost', sa.Float(), nullable=True, comment='运输成本'),
    sa.Column('scale_cost', sa.Float(), nullable=True, comment='规模成本'),
    sa.Column('total_cost', sa.Float(), nullable=True, comment='总成本'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wc_father_t01_sku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c01_sku_id', sa.String(length=50), nullable=True, comment='料件编号'),
    sa.Column('c01_sku_name', sa.String(length=50), nullable=True, comment='品名'),
    sa.Column('c02_sku_history_sector', sa.String(length=255), nullable=True, comment='历史排产员字典'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wc_father_t02_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c01_sku_id', sa.String(length=50), nullable=True, comment='料件编号'),
    sa.Column('c02_father', sa.String(length=50), nullable=True, comment='父料号'),
    sa.Column('c03_son', sa.String(length=50), nullable=True, comment='子料号'),
    sa.Column('c04_root_style', sa.String(length=50), nullable=True, comment='节点类型'),
    sa.Column('c05_son_name', sa.String(length=50), nullable=True, comment='品名'),
    sa.Column('c06_standard_output', sa.String(length=50), nullable=True, comment='标准产能'),
    sa.Column('c07_person_plan', sa.String(length=50), nullable=True, comment='计划人数'),
    sa.Column('c08_group_leader_num', sa.String(length=50), nullable=True, comment='班组长人数'),
    sa.Column('c09_device_type', sa.String(length=50), nullable=True, comment='设备类型'),
    sa.Column('c10_production_type', sa.String(length=50), nullable=True, comment='生产方式'),
    sa.Column('c11_near_match', sa.String(length=50), nullable=True, comment='近似匹配'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_cy____prj_main',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('prj_create_t', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('prj_creator', sa.String(length=255), nullable=True, comment='创建人'),
    sa.Column('last_refresh_t', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('prj_process_text', sa.String(length=255), nullable=True, comment='项目进度说明'),
    sa.Column('prj_process_int', sa.Integer(), nullable=True, comment='项目进度条'),
    sa.Column('prj_run_state_text', sa.String(length=255), nullable=True, comment='运行状态'),
    sa.Column('prj_run_error_text', sa.String(length=255), nullable=True, comment='报错信息'),
    sa.Column('prj_note', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prj_name')
    )
    op.create_table('workshop_cy_input01_ws_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='车间'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_name', sa.String(length=50), nullable=True, comment='名称'),
    sa.Column('c02_value', sa.String(length=255), nullable=True, comment='值'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_cy_input02_planer_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='车间'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_staff_name', sa.String(length=50), nullable=True, comment='姓名'),
    sa.Column('c02_staff_id', sa.String(length=50), nullable=True, comment='工号'),
    sa.Column('c02_staff_time', sa.String(length=50), nullable=True, comment='负责时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_cy_input03_sku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='车间'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_sku_id', sa.String(length=50), nullable=True, comment='料件编号'),
    sa.Column('c02_sku_name', sa.String(length=50), nullable=True, comment='料件名称'),
    sa.Column('c03_sku_relate_staff', sa.String(length=50), nullable=True, comment='料件关联排产员工号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_cy_input04_worker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='车间'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_worker_name', sa.String(length=50), nullable=True, comment='姓名'),
    sa.Column('c02_worker_id', sa.String(length=50), nullable=True, comment='工号'),
    sa.Column('c03_worker_type', sa.String(length=50), nullable=True, comment='工种'),
    sa.Column('c04_is_formal', sa.String(length=50), nullable=True, comment='是否是正式工'),
    sa.Column('c04_sku_maintenance_state', sa.String(length=10), nullable=True, comment='是否手工维护'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_cy_input05_machine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='车间'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_worker_name', sa.String(length=50), nullable=True, comment='姓名'),
    sa.Column('c02_worker_id', sa.String(length=50), nullable=True, comment='工号'),
    sa.Column('c03_worker_type', sa.String(length=50), nullable=True, comment='工种'),
    sa.Column('c04_is_formal', sa.String(length=50), nullable=True, comment='是否是正式工'),
    sa.Column('c04_sku_maintenance_state', sa.String(length=10), nullable=True, comment='是否手工维护'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_cy_input06_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='车间'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_m_name', sa.String(length=50), nullable=True, comment='物料名称'),
    sa.Column('c02_m_arrival_t', sa.String(length=50), nullable=True, comment='到货时间'),
    sa.Column('c03_m_num', sa.String(length=50), nullable=True, comment='数量'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_cy_input07_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='车间'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_m_id', sa.String(length=50), nullable=True, comment='料件编号'),
    sa.Column('c02_f_m_id', sa.String(length=50), nullable=True, comment='父料号'),
    sa.Column('c03_s_m_id', sa.String(length=50), nullable=True, comment='子料号'),
    sa.Column('c04_s_m_id', sa.String(length=50), nullable=True, comment='节点类型'),
    sa.Column('c05_m_name', sa.String(length=50), nullable=True, comment='品名'),
    sa.Column('c06_standard_output', sa.String(length=50), nullable=True, comment='标准产能'),
    sa.Column('c07_person_need', sa.String(length=50), nullable=True, comment='计划人数'),
    sa.Column('c08_group_leader_num', sa.String(length=50), nullable=True, comment='班组长人数'),
    sa.Column('c09_device_type', sa.String(length=50), nullable=True, comment='设备类型'),
    sa.Column('c10_production_type', sa.String(length=50), nullable=True, comment='生产方式'),
    sa.Column('c11_match', sa.String(length=50), nullable=True, comment='近似匹配'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop_cy_input07_process')
    op.drop_table('workshop_cy_input06_material')
    op.drop_table('workshop_cy_input05_machine')
    op.drop_table('workshop_cy_input04_worker')
    op.drop_table('workshop_cy_input03_sku')
    op.drop_table('workshop_cy_input02_planer_history')
    op.drop_table('workshop_cy_input01_ws_info')
    op.drop_table('workshop_cy____prj_main')
    op.drop_table('wc_father_t02_process')
    op.drop_table('wc_father_t01_sku')
    op.drop_table('sjtu_pmedian_output_3_costmatrix')
    op.drop_table('sjtu_pmedian_output_2_buildscale')
    op.drop_table('sjtu_pmedian_output_1_allocationmatrix')
    op.drop_table('sjtu_pmedian_input4_costmatrix')
    op.drop_table('sjtu_pmedian_input3_recyclingcenter')
    op.drop_table('sjtu_pmedian_input2_transferstation')
    op.drop_table('sjtu_pmedian_input1_basic')
    op.drop_table('sjtu_pmedian____prj_main')
    op.drop_table('sjtu_carbon_emission_output1_carbon_emission_result')
    op.drop_table('sjtu_carbon_emission_input4_region_detail')
    op.drop_table('sjtu_carbon_emission_input3_regionfactor')
    op.drop_table('sjtu_carbon_emission_input2_region_info')
    op.drop_table('sjtu_carbon_emission_input1_region_msw_generation')
    op.drop_table('sjtu_carbon_emission____prj_main')
    # ### end Alembic commands ###
