"""empty message

Revision ID: 9e753a422f88
Revises: 
Create Date: 2021-12-09 22:40:40.331481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e753a422f88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_sql_bi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c01_name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('c02_cols_str', sa.String(length=255), nullable=True, comment='表头字段'),
    sa.Column('c03_sql_str', sa.String(length=1255), nullable=True, comment='SQL语句'),
    sa.Column('c04_bar', sa.String(length=50), nullable=True, comment='bar参数'),
    sa.Column('c05_bar_group', sa.String(length=255), nullable=True, comment='bar_group参数'),
    sa.Column('c06_pie', sa.String(length=255), nullable=True, comment='pie参数'),
    sa.Column('c07_sankey', sa.String(length=255), nullable=True, comment='sankey参数'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autohtmlcontainers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('html_name', sa.String(length=255), nullable=False, comment='页面名称'),
    sa.Column('container_name', sa.String(length=255), nullable=True, comment='图表名称'),
    sa.Column('container_skip_url', sa.String(length=255), nullable=True, comment='图表跳转链接'),
    sa.Column('container_col_long', sa.Integer(), nullable=True, comment='图表宽度'),
    sa.Column('container_chart_type', sa.String(length=255), nullable=True, comment='图表类型'),
    sa.Column('container_data_url', sa.String(length=255), nullable=False, comment='图表数据地址'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects____prj_main',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('prj_create_t', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('prj_creator', sa.String(length=255), nullable=True, comment='创建人'),
    sa.Column('last_refresh_t', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('prj_process_text', sa.String(length=255), nullable=True, comment='项目进度说明'),
    sa.Column('prj_process_int', sa.Integer(), nullable=True, comment='项目进度条'),
    sa.Column('prj_run_state_text', sa.String(length=255), nullable=True, comment='运行状态'),
    sa.Column('prj_run_error_text', sa.String(length=255), nullable=True, comment='报错信息'),
    sa.Column('prj_note', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prj_name')
    )
    op.create_table('scheduling_projects_input1_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_date', sa.Date(), nullable=True, comment='接单日期'),
    sa.Column('c02_customer', sa.String(length=50), nullable=True, comment='客户'),
    sa.Column('c03_catagory', sa.String(length=50), nullable=True, comment='产品分类'),
    sa.Column('c04_product_type', sa.String(length=50), nullable=True, comment='产品属性'),
    sa.Column('c05_plan', sa.String(length=10), nullable=True, comment='是否纳入计划'),
    sa.Column('c06_id_num', sa.String(length=50), nullable=True, comment='订单号'),
    sa.Column('c07_fast_id', sa.String(length=50), nullable=True, comment='快捷编号'),
    sa.Column('c08_product_id', sa.String(length=50), nullable=True, comment='产品编号'),
    sa.Column('c09_num_need', sa.Integer(), nullable=False, comment='订单数量'),
    sa.Column('c10_num_finish', sa.Integer(), nullable=True, comment='完工数量'),
    sa.Column('c11_lishu', sa.String(length=50), nullable=True, comment='粒数'),
    sa.Column('c12_delivery_date', sa.Date(), nullable=True, comment='订单交期'),
    sa.Column('c13_material_state', sa.String(length=50), nullable=True, comment='物料状态'),
    sa.Column('c14lack_material_id', sa.String(length=50), nullable=True, comment='缺货料号'),
    sa.Column('c15_lack_get_date', sa.Date(), nullable=True, comment='预计到货时间'),
    sa.Column('c16_priority1', sa.String(length=10), nullable=True, comment='订单优先级'),
    sa.Column('c17_catagory_1', sa.String(length=50), nullable=True, comment='订单分类'),
    sa.Column('c18_plan_start_d', sa.String(length=255), nullable=True, comment='计划开始时间'),
    sa.Column('c19_plan_end_d', sa.String(length=255), nullable=True, comment='计划结束时间'),
    sa.Column('c20_state', sa.String(length=255), nullable=True, comment='订单状态'),
    sa.Column('c21_actual_start_t', sa.String(length=255), nullable=True, comment='实际开始时间'),
    sa.Column('c22_actual_end_t', sa.String(length=255), nullable=True, comment='实际结束时间'),
    sa.Column('c23_note1', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_input2_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_p_product_id', sa.String(length=50), nullable=True, comment='产品编号'),
    sa.Column('c02_f_product_id', sa.String(length=50), nullable=True, comment='父料号'),
    sa.Column('c03_son_product_id', sa.String(length=50), nullable=True, comment='子料号'),
    sa.Column('c04_product_name', sa.String(length=50), nullable=True, comment='品名'),
    sa.Column('c05_district', sa.String(length=50), nullable=True, comment='区域'),
    sa.Column('c06_work_line', sa.String(length=50), nullable=True, comment='产线'),
    sa.Column('c07_person_district', sa.String(length=50), nullable=True, comment='人员区域'),
    sa.Column('c08_person_num', sa.String(length=50), nullable=False, comment='计划人数'),
    sa.Column('c09_group_leader_num', sa.Integer(), nullable=False, comment='班组长人数'),
    sa.Column('c10_machine_operator_num', sa.Integer(), nullable=False, comment='操机手人数'),
    sa.Column('c11_device_type', sa.String(length=50), nullable=True, comment='设备类型'),
    sa.Column('c12_device_num', sa.String(length=50), nullable=True, comment='设备数量'),
    sa.Column('c13_device_standard_output', sa.String(length=50), nullable=True, comment='标准产能'),
    sa.Column('c14_transfer_time_lower', sa.String(length=50), nullable=True, comment='转移时间下限'),
    sa.Column('c15_transfer_time_upper', sa.String(length=50), nullable=True, comment='转移时间上限'),
    sa.Column('c16_constraint_type', sa.String(length=10), nullable=True, comment='约束类型'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_input3_person',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_person_district', sa.String(length=50), nullable=True, comment='人员区域'),
    sa.Column('c02_person_group', sa.String(length=50), nullable=True, comment='班组'),
    sa.Column('c03_p_priority', sa.String(length=10), nullable=True, comment='优先级'),
    sa.Column('c04_group_name', sa.String(length=50), nullable=True, comment='班次'),
    sa.Column('c05_transfer_start_t', sa.Date(), nullable=True, comment='切换起始时间'),
    sa.Column('c06_transfer_period', sa.Integer(), nullable=False, comment='切换周期'),
    sa.Column('c07_person_count', sa.Integer(), nullable=False, comment='合计人数'),
    sa.Column('c08_group_leader_num', sa.Integer(), nullable=False, comment='班组长人数'),
    sa.Column('c09_leader_ability_type', sa.String(length=50), nullable=True, comment='能力标签'),
    sa.Column('c10_machine_operator_num', sa.Integer(), nullable=False, comment='操机手人数'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_input4_person_holiday',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_person_name', sa.String(length=50), nullable=True, comment='员工'),
    sa.Column('c02_person_district', sa.String(length=50), nullable=True, comment='人员区域'),
    sa.Column('c03_group_name', sa.String(length=50), nullable=True, comment='班组'),
    sa.Column('c04_is_leader', sa.String(length=10), nullable=True, comment='是否班组长'),
    sa.Column('c05_leader_ability_type', sa.String(length=5), nullable=True, comment='能力标签'),
    sa.Column('c06_is_operator', sa.String(length=10), nullable=True, comment='是否操机手'),
    sa.Column('c07_holiday_start_t', sa.Date(), nullable=True, comment='请假开始时间'),
    sa.Column('c08_holiday_end_t', sa.Date(), nullable=True, comment='请假结束时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_input5_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_device_type', sa.String(length=10), nullable=True, comment='设备类型'),
    sa.Column('c02_device_id', sa.String(length=50), nullable=True, comment='设备编号'),
    sa.Column('c03_device_name', sa.String(length=50), nullable=True, comment='设备名称'),
    sa.Column('c04_device_state', sa.String(length=50), nullable=True, comment='设备状态'),
    sa.Column('c05_device_ability', sa.String(length=50), nullable=True, comment='设备能力'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_input6_bom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_product_id', sa.String(length=50), nullable=True, comment='产品编号'),
    sa.Column('c02_father_m', sa.String(length=50), nullable=True, comment='父料号'),
    sa.Column('c03_son_m', sa.String(length=50), nullable=True, comment='子料号'),
    sa.Column('c04_product_name', sa.String(length=50), nullable=True, comment='品名'),
    sa.Column('c05_component', sa.String(length=50), nullable=True, comment='组成用量'),
    sa.Column('c06_main_num', sa.String(length=50), nullable=True, comment='主件底数'),
    sa.Column('c07_unit', sa.String(length=10), nullable=True, comment='单位'),
    sa.Column('c08_cost_rate', sa.String(length=50), nullable=True, comment='损耗率'),
    sa.Column('c09_main_type', sa.String(length=50), nullable=True, comment='料件属性'),
    sa.Column('c10_bom_note', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_input7_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_m_id', sa.String(length=50), nullable=True, comment='元件料号'),
    sa.Column('c02_product_name', sa.String(length=50), nullable=True, comment='品名'),
    sa.Column('c03_m_unit', sa.String(length=10), nullable=True, comment='发料单位'),
    sa.Column('c04_m_num', sa.Float(), nullable=True, comment='库存可用量'),
    sa.Column('r_t01', sa.Date(), nullable=True, comment='预计到货时间01'),
    sa.Column('r_t01n01', sa.Float(), nullable=True, comment='预计到货数量01'),
    sa.Column('r_t02', sa.Date(), nullable=True, comment='预计到货时间02'),
    sa.Column('r_t02n02', sa.Float(), nullable=True, comment='预计到货数量02'),
    sa.Column('r_t03', sa.Date(), nullable=True, comment='预计到货时间03'),
    sa.Column('r_t03n03', sa.Float(), nullable=True, comment='预计到货数量03'),
    sa.Column('r_t04', sa.Date(), nullable=True, comment='预计到货时间04'),
    sa.Column('r_t04n04', sa.Float(), nullable=True, comment='预计到货数量04'),
    sa.Column('r_t05', sa.Date(), nullable=True, comment='预计到货时间05'),
    sa.Column('r_t05n05', sa.Float(), nullable=True, comment='预计到货数量05'),
    sa.Column('r_t06', sa.Date(), nullable=True, comment='预计到货时间06'),
    sa.Column('r_t06n06', sa.Float(), nullable=True, comment='预计到货数量06'),
    sa.Column('r_t07', sa.Date(), nullable=True, comment='预计到货时间07'),
    sa.Column('r_t07n07', sa.Float(), nullable=True, comment='预计到货数量07'),
    sa.Column('r_t08', sa.Date(), nullable=True, comment='预计到货时间08'),
    sa.Column('r_t08n08', sa.Float(), nullable=True, comment='预计到货数量08'),
    sa.Column('r_t09', sa.Date(), nullable=True, comment='预计到货时间09'),
    sa.Column('r_t09n09', sa.Float(), nullable=True, comment='预计到货数量09'),
    sa.Column('r_t10', sa.Date(), nullable=True, comment='预计到货时间10'),
    sa.Column('r_t10n10', sa.Float(), nullable=True, comment='预计到货数量10'),
    sa.Column('r_t11', sa.Date(), nullable=True, comment='预计到货时间11'),
    sa.Column('r_t11n11', sa.Float(), nullable=True, comment='预计到货数量11'),
    sa.Column('r_t12', sa.Date(), nullable=True, comment='预计到货时间12'),
    sa.Column('r_t12n12', sa.Float(), nullable=True, comment='预计到货数量12'),
    sa.Column('r_t13', sa.Date(), nullable=True, comment='预计到货时间13'),
    sa.Column('r_t13n13', sa.Float(), nullable=True, comment='预计到货数量13'),
    sa.Column('r_t14', sa.Date(), nullable=True, comment='预计到货时间14'),
    sa.Column('r_t14n14', sa.Float(), nullable=True, comment='预计到货数量14'),
    sa.Column('r_t15', sa.Date(), nullable=True, comment='预计到货时间15'),
    sa.Column('r_t15n15', sa.Float(), nullable=True, comment='预计到货数量15'),
    sa.Column('r_t16', sa.Date(), nullable=True, comment='预计到货时间16'),
    sa.Column('r_t16n16', sa.Float(), nullable=True, comment='预计到货数量16'),
    sa.Column('r_t17', sa.Date(), nullable=True, comment='预计到货时间17'),
    sa.Column('r_t17n17', sa.Float(), nullable=True, comment='预计到货数量17'),
    sa.Column('r_t18', sa.Date(), nullable=True, comment='预计到货时间18'),
    sa.Column('r_t18n18', sa.Float(), nullable=True, comment='预计到货数量18'),
    sa.Column('r_t19', sa.Date(), nullable=True, comment='预计到货时间19'),
    sa.Column('r_t19n19', sa.Float(), nullable=True, comment='预计到货数量19'),
    sa.Column('r_t20', sa.Date(), nullable=True, comment='预计到货时间20'),
    sa.Column('r_t20n20', sa.Float(), nullable=True, comment='预计到货数量20'),
    sa.Column('r_t21', sa.Date(), nullable=True, comment='预计到货时间21'),
    sa.Column('r_t21n21', sa.Float(), nullable=True, comment='预计到货数量21'),
    sa.Column('r_t22', sa.Date(), nullable=True, comment='预计到货时间22'),
    sa.Column('r_t22n22', sa.Float(), nullable=True, comment='预计到货数量22'),
    sa.Column('r_t23', sa.Date(), nullable=True, comment='预计到货时间23'),
    sa.Column('r_t23n23', sa.Float(), nullable=True, comment='预计到货数量23'),
    sa.Column('r_t24', sa.Date(), nullable=True, comment='预计到货时间24'),
    sa.Column('r_t24n24', sa.Float(), nullable=True, comment='预计到货数量24'),
    sa.Column('r_t25', sa.Date(), nullable=True, comment='预计到货时间25'),
    sa.Column('r_t25n25', sa.Float(), nullable=True, comment='预计到货数量25'),
    sa.Column('r_t26', sa.Date(), nullable=True, comment='预计到货时间26'),
    sa.Column('r_t26n26', sa.Float(), nullable=True, comment='预计到货数量26'),
    sa.Column('r_t27', sa.Date(), nullable=True, comment='预计到货时间27'),
    sa.Column('r_t27n27', sa.Float(), nullable=True, comment='预计到货数量27'),
    sa.Column('r_t28', sa.Date(), nullable=True, comment='预计到货时间28'),
    sa.Column('r_t28n28', sa.Float(), nullable=True, comment='预计到货数量28'),
    sa.Column('r_t29', sa.Date(), nullable=True, comment='预计到货时间29'),
    sa.Column('r_t29n29', sa.Float(), nullable=True, comment='预计到货数量29'),
    sa.Column('r_t30', sa.Date(), nullable=True, comment='预计到货时间30'),
    sa.Column('r_t30n30', sa.Float(), nullable=True, comment='预计到货数量30'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_input8_calender',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c1_resource', sa.String(length=50), nullable=True, comment='资源'),
    sa.Column('c2_work_day', sa.String(length=255), nullable=True, comment='出勤日期或星期'),
    sa.Column('c3_work_mode', sa.String(length=255), nullable=True, comment='出勤模式或时间'),
    sa.Column('c4_work_priority', sa.String(length=10), nullable=True, comment='优先级'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_input9_workmode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c1_work_mode1', sa.String(length=50), nullable=True, comment='出勤模式'),
    sa.Column('c2_work_day', sa.String(length=255), nullable=True, comment='工作时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_output_1_workno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c01_work_no', sa.String(length=255), nullable=True, comment='工单编号'),
    sa.Column('c02_district', sa.String(length=50), nullable=True, comment='区域'),
    sa.Column('c03_workline', sa.String(length=50), nullable=True, comment='产线'),
    sa.Column('c04_order_num_id', sa.String(length=50), nullable=True, comment='订单号'),
    sa.Column('c05_order_fast_id', sa.String(length=50), nullable=True, comment='快捷编号'),
    sa.Column('c06_product_id', sa.String(length=50), nullable=True, comment='产品编号'),
    sa.Column('c07_order_num_need', sa.Integer(), nullable=True, comment='订单数量'),
    sa.Column('c08_order_delivery_date', sa.Date(), nullable=True, comment='订单交期'),
    sa.Column('c09_material_lack_id', sa.String(length=255), nullable=True, comment='缺货料号'),
    sa.Column('c10_material_lack_arrival_t', sa.Date(), nullable=True, comment='预计到货时间'),
    sa.Column('c11_order_priority', sa.String(length=20), nullable=True, comment='订单优先级'),
    sa.Column('c12_father_m_id', sa.String(length=50), nullable=True, comment='父料号'),
    sa.Column('c13_son_m_id', sa.String(length=50), nullable=True, comment='子料号'),
    sa.Column('c14_product_name', sa.String(length=50), nullable=True, comment='品名'),
    sa.Column('c15_person_district_name', sa.String(length=50), nullable=True, comment='人员区域'),
    sa.Column('c16_person_plan_num', sa.String(length=50), nullable=True, comment='计划人数'),
    sa.Column('c17_group_leader_num', sa.String(length=50), nullable=True, comment='班组长人数'),
    sa.Column('c18_operator_num', sa.String(length=50), nullable=True, comment='操机手人数'),
    sa.Column('c19_device_type', sa.String(length=50), nullable=True, comment='设备类型'),
    sa.Column('c20_device_num', sa.String(length=50), nullable=True, comment='设备数量'),
    sa.Column('c21_device_standard_output', sa.String(length=50), nullable=True, comment='标准产能'),
    sa.Column('c22_transfer_t_lower', sa.String(length=50), nullable=True, comment='转移时间下限'),
    sa.Column('c23_transfer_t_upper', sa.String(length=50), nullable=True, comment='转移时间上限'),
    sa.Column('c24_constraint_type', sa.String(length=255), nullable=True, comment='约束类型'),
    sa.Column('c25_is_fixed', sa.String(length=10), nullable=True, comment='是否固定'),
    sa.Column('c26_fixed_t', sa.String(length=50), nullable=True, comment='固定时间'),
    sa.Column('c27_plan_start_t', sa.String(length=50), nullable=True, comment='计划开始时间'),
    sa.Column('c28_plan_last_t', sa.Float(), nullable=True, comment='计划持续时长'),
    sa.Column('c29_plan_end_t', sa.String(length=50), nullable=True, comment='计划结束时间'),
    sa.Column('c30_actual_start_t', sa.String(length=50), nullable=True, comment='实际开始时间'),
    sa.Column('c31_actual_end_t', sa.String(length=50), nullable=True, comment='实际结束时间'),
    sa.Column('c32_work_no_state', sa.String(length=50), nullable=True, comment='工单状态'),
    sa.Column('c33_allocate_p', sa.String(length=255), nullable=True, comment='分配人员'),
    sa.Column('c34_allocate_leader', sa.String(length=255), nullable=True, comment='分配班组长'),
    sa.Column('c35_allocate_operator', sa.String(length=255), nullable=True, comment='分配操机手'),
    sa.Column('c36_finished_num', sa.String(length=50), nullable=True, comment='已完成数量'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_output_2_material_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c1_material_num_id', sa.String(length=50), nullable=True, comment='元件料号'),
    sa.Column('c2_product_name', sa.String(length=50), nullable=True, comment='品名'),
    sa.Column('c3_m_unit', sa.String(length=50), nullable=True, comment='发料单位'),
    sa.Column('c4_order_num_id', sa.String(length=50), nullable=True, comment='订单号'),
    sa.Column('c5_product_num_id', sa.String(length=50), nullable=True, comment='产品编号'),
    sa.Column('c6_product_need_num', sa.Float(), nullable=False, comment='需求数量'),
    sa.Column('c7_product_need_t', sa.String(length=50), nullable=True, comment='需求时间'),
    sa.Column('c8_p_reserve_num', sa.Float(), nullable=False, comment='库存结余'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_projects_output_3_result_run_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prj_name', sa.String(length=255), nullable=False, comment='项目名'),
    sa.Column('d_insert_t', sa.String(length=50), nullable=True, comment='导入时间'),
    sa.Column('c1_run_cost_time_second', sa.String(length=255), nullable=True, comment='运行耗时'),
    sa.Column('c2_order_delay_hour', sa.String(length=255), nullable=True, comment='延期时间'),
    sa.Column('c3_order_finish_datetime', sa.String(length=255), nullable=True, comment='完工时间'),
    sa.Column('c4_test1', sa.Integer(), nullable=False, comment='整数测试'),
    sa.Column('c5_test2', sa.Float(), nullable=False, comment='小数测试'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test11', sa.String(length=50), nullable=True, comment='测试1'),
    sa.Column('test22', sa.String(length=50), nullable=True, comment='测试2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=50), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('role', sa.String(length=50), nullable=True, comment='角色'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('test1')
    op.drop_table('scheduling_projects_output_3_result_run_info')
    op.drop_table('scheduling_projects_output_2_material_check')
    op.drop_table('scheduling_projects_output_1_workno')
    op.drop_table('scheduling_projects_input9_workmode')
    op.drop_table('scheduling_projects_input8_calender')
    op.drop_table('scheduling_projects_input7_material')
    op.drop_table('scheduling_projects_input6_bom')
    op.drop_table('scheduling_projects_input5_device')
    op.drop_table('scheduling_projects_input4_person_holiday')
    op.drop_table('scheduling_projects_input3_person')
    op.drop_table('scheduling_projects_input2_process')
    op.drop_table('scheduling_projects_input1_order')
    op.drop_table('scheduling_projects____prj_main')
    op.drop_table('autohtmlcontainers')
    op.drop_table('auto_sql_bi')
    # ### end Alembic commands ###
